"""Seed catalog of fundamental intake units, whole foods, and staples."""

from oopple.domain.enums import CuisineType, ItemCategory, UnitType

SEED_INTAKE_UNITS = [
    {
        "sku": "OO-WATER-001",
        "name": "Pure Spring Water",
        "brand": "Oopple Baseline",
        "barcode": "000000000001",
        "cuisine_type": CuisineType.BEVERAGE,
        "category": ItemCategory.BEVERAGE,
        "serving_size": 250.0,
        "serving_unit": UnitType.MILLILITER,
        "calories": 0.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 0.0,
        "fiber_g": 0.0,
        "sodium_mg": 5.0,
        "water_ml": 250.0,
        "shelf_life_pantry_days": 365,
        "shelf_life_fridge_days": 365,
        "default_cost": 0.0,
        "tags": "hydration,essential,baseline,zero-cal",
    },
    {
        "sku": "OO-CHICKEN-001",
        "name": "Boneless Skinless Chicken Breast",
        "brand": "Fresh Harvest",
        "barcode": "000000000002",
        "cuisine_type": CuisineType.GLOBAL,
        "category": ItemCategory.PROTEIN,
        "serving_size": 100.0,
        "serving_unit": UnitType.GRAM,
        "calories": 165.0,
        "protein_g": 31.0,
        "carbs_g": 0.0,
        "fat_g": 3.6,
        "fiber_g": 0.0,
        "sodium_mg": 74.0,
        "water_ml": 65.0,
        "shelf_life_fridge_days": 4,
        "shelf_life_freezer_days": 180,
        "default_cost": 4.99,
        "tags": "protein,lean,poultry",
    },
    {
        "sku": "OO-SALMON-001",
        "name": "Wild Atlantic Salmon Fillet",
        "brand": "Ocean Catch",
        "barcode": "000000000003",
        "cuisine_type": CuisineType.NORDIC,
        "category": ItemCategory.PROTEIN,
        "serving_size": 100.0,
        "serving_unit": UnitType.GRAM,
        "calories": 208.0,
        "protein_g": 20.0,
        "carbs_g": 0.0,
        "fat_g": 13.0,
        "fiber_g": 0.0,
        "sodium_mg": 59.0,
        "water_ml": 68.0,
        "shelf_life_fridge_days": 3,
        "shelf_life_freezer_days": 120,
        "default_cost": 8.99,
        "tags": "protein,omega3,seafood",
    },
    {
        "sku": "OO-EGGS-001",
        "name": "Pasture-Raised Large Eggs",
        "brand": "Meadow Farm",
        "barcode": "000000000004",
        "cuisine_type": CuisineType.GLOBAL,
        "category": ItemCategory.DAIRY,
        "serving_size": 1.0,
        "serving_unit": UnitType.PIECE,
        "calories": 72.0,
        "protein_g": 6.3,
        "carbs_g": 0.4,
        "fat_g": 4.8,
        "fiber_g": 0.0,
        "sodium_mg": 71.0,
        "water_ml": 38.0,
        "shelf_life_fridge_days": 35,
        "default_cost": 4.50,
        "tags": "protein,breakfast,staple",
    },
    {
        "sku": "OO-RICE-001",
        "name": "Jasmine White Rice",
        "brand": "Golden Lotus",
        "barcode": "000000000005",
        "cuisine_type": CuisineType.ASIAN,
        "category": ItemCategory.GRAIN,
        "serving_size": 100.0,
        "serving_unit": UnitType.GRAM,
        "calories": 130.0,
        "protein_g": 2.7,
        "carbs_g": 28.0,
        "fat_g": 0.3,
        "fiber_g": 0.4,
        "sodium_mg": 1.0,
        "water_ml": 68.0,
        "shelf_life_pantry_days": 365,
        "default_cost": 2.29,
        "tags": "grain,staple,carbs",
    },
    {
        "sku": "OO-SPINACH-001",
        "name": "Baby Spinach Leaves",
        "brand": "Organic Greens",
        "barcode": "000000000006",
        "cuisine_type": CuisineType.MEDITERRANEAN,
        "category": ItemCategory.PRODUCE,
        "serving_size": 100.0,
        "serving_unit": UnitType.GRAM,
        "calories": 23.0,
        "protein_g": 2.9,
        "carbs_g": 3.6,
        "fat_g": 0.4,
        "fiber_g": 2.2,
        "sodium_mg": 79.0,
        "water_ml": 91.0,
        "shelf_life_fridge_days": 7,
        "default_cost": 2.99,
        "tags": "produce,greens,iron,vitamins",
    },
    {
        "sku": "OO-APPLE-001",
        "name": "Honeycrisp Apple",
        "brand": "Orchard Fresh",
        "barcode": "000000000007",
        "cuisine_type": CuisineType.AMERICANA,
        "category": ItemCategory.PRODUCE,
        "serving_size": 1.0,
        "serving_unit": UnitType.PIECE,
        "calories": 95.0,
        "protein_g": 0.5,
        "carbs_g": 25.0,
        "fat_g": 0.3,
        "fiber_g": 4.4,
        "sodium_mg": 2.0,
        "water_ml": 150.0,
        "shelf_life_fridge_days": 28,
        "shelf_life_counter_days": 10,
        "default_cost": 1.25,
        "tags": "fruit,sweet,snack,hydration",
    },
    {
        "sku": "OO-OLIVEOIL-001",
        "name": "Extra Virgin Olive Oil",
        "brand": "Mediterranean Valley",
        "barcode": "000000000008",
        "cuisine_type": CuisineType.MEDITERRANEAN,
        "category": ItemCategory.CONDIMENT,
        "serving_size": 15.0,
        "serving_unit": UnitType.MILLILITER,
        "calories": 119.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 13.5,
        "fiber_g": 0.0,
        "sodium_mg": 0.0,
        "water_ml": 0.0,
        "shelf_life_pantry_days": 365,
        "default_cost": 9.99,
        "tags": "healthy-fats,culinary-oil,cooking",
    },
    {
        "sku": "OO-GARDEN-BASIL-001",
        "name": "Fresh Sweet Garden Basil",
        "brand": "Home Garden",
        "barcode": None,
        "cuisine_type": CuisineType.ITALIAN,
        "category": ItemCategory.SPICE,
        "serving_size": 10.0,
        "serving_unit": UnitType.GRAM,
        "calories": 2.0,
        "protein_g": 0.3,
        "carbs_g": 0.3,
        "fat_g": 0.1,
        "fiber_g": 0.2,
        "sodium_mg": 1.0,
        "water_ml": 9.0,
        "shelf_life_counter_days": 4,
        "shelf_life_fridge_days": 7,
        "default_cost": 0.0,
        "tags": "garden_harvest,herb,fresh,aromatic",
    },
    {
        "sku": "OO-MILK-001",
        "name": "Whole Vitamin D Milk",
        "brand": "Clover Valley",
        "barcode": "000000000009",
        "cuisine_type": CuisineType.AMERICANA,
        "category": ItemCategory.DAIRY,
        "serving_size": 240.0,
        "serving_unit": UnitType.MILLILITER,
        "calories": 149.0,
        "protein_g": 7.7,
        "carbs_g": 11.7,
        "fat_g": 7.9,
        "fiber_g": 0.0,
        "sodium_mg": 105.0,
        "water_ml": 210.0,
        "shelf_life_fridge_days": 10,
        "default_cost": 3.79,
        "tags": "dairy,calcium,hydration",
    },
    {
        "sku": "OO-YOGURT-001",
        "name": "Plain Whole Milk Greek Yogurt",
        "brand": "Olympus",
        "barcode": "000000000010",
        "cuisine_type": CuisineType.MEDITERRANEAN,
        "category": ItemCategory.DAIRY,
        "serving_size": 150.0,
        "serving_unit": UnitType.GRAM,
        "calories": 140.0,
        "protein_g": 15.0,
        "carbs_g": 6.0,
        "fat_g": 6.0,
        "fiber_g": 0.0,
        "sodium_mg": 50.0,
        "water_ml": 125.0,
        "shelf_life_fridge_days": 18,
        "default_cost": 4.49,
        "tags": "dairy,probiotic,protein",
    },
]
